### ISSUE TITLE
Conflict with Edit Flow's custom status module

### ISSUE THREAD

**Issue by su** [aurovrata/ReOrder-posts-within-categories#1]
Hi.
I ran into the same problems people have been complaining about in this plugin's support area at wp.org and saw your patch, which I installed. It partially fixes things(no more French), but the plugin still fails to list entries once a category was selected.

I was able to track this down to the Custom Status module of Edit Flow, which I use. Disabling just that, not even the entire Edit Flow collection, restores expected functionality.

Given the module provides post statuses, it might initially seem that this has nothing to do with you, but the thing is that upon arriving at the sorting page, this JS error is thrown: 

    Error: ReferenceError: current_user_can_publish_posts is not defined
    Source File: […]/wp-content/plugins/edit-flow/modules/custom-status/lib/custom-status.js?ver=0.8

Given that what you were doing with this patch was modifying who's allowed to make use of the plugin, it seems like there's at least some chance the problem is coming from your end of things and you might want to have a look.

I tried a quick scan to see if I could identify the problem more specifically but your edits were more extensive than I expected and I have a deadline coming up for a client at the moment. I might give it another try over the weekend.

**Comment by aurovrata** [comment]
Hi Su

thanks for your mail. 

**First**, It sounds like your Custom Status plugin is making use of independent tables to store posts statuses.  If this is the case, then it is most likely invoking the 'pre_get_post' or 'posts_where' hook in order to include status conditions to DB queries.
Re-Order post makes extensive use of 'posts_where' (line 93 in reorder-posts-within-categories.php), 'posts_join' (line 67 in reorder-posts-within-categories.php) and 'posts_orderby' (line 110 in reorder-posts-within-categories.php) hooks and this may be where the conflict arises.
To debug this, I would suggest you use the [Save Queries debug options of Wordpress](https://codex.wordpress.org/Debugging_in_WordPress#SAVEQUERIES), and log the queries once they are returned to see if the Re-Order tables are being queries or not.

**Second**, the js error is strange.  I doubt very much it is caused by the changes I made.  To give editors access to the functionality I simply ensured the menu is visible in their dashboard (see line 379 & 383 in reorder-posts-within-categories.php).  Hence very unlikely it is afffecting the js in your plugin.

On the other hand there may be other js conflicts arising from the Re-Order plugin which I am not aware of.  Frankly, I have not really gone through the code in detail (just skimmed over it to understand the basic functionality and know where to look to fix things).  Sorry, can't help you much more here.

**Third** there is another simple hack you can use to ensure a certain order of posts.  I have used this in the past to ensure a certain order to featured slides.  You can pick up the gist of it from the [WP TwentyFourteen  theme mods](http://wordpress.syllogic.in/2014/10/unleashing-wp-twenty14-rhs/) we made.  The basic idea is to use post slugs to order query alphabetically by slug name.  It works well but obviously not a very nice solution for a clueless client, but if you maintain the site yourself it's very easy to implement.  You need to capture the queries with 'pre_get_post' hooks and tweak them to ensure the order is done on the slug.

Let me know if you're stuck :)

**Comment by su** [comment]
[Edit Flow isn't mine; it's maintained by Automattic.]

No, you're right. 
I'm still not sure if it's ultimately because of Edit Flow being sloppy, or if Reorder should have done something a little differently, but this isn't coming from your edits. 

I found a hack that resolves the problem, which I'll post after I get through this deadline, at least for documentation in case someone else runs into this.

**Comment by aurovrata** [comment]
That would be nice.... good luck :)

**Comment by su** [comment]
I posted the hack [here](https://wordpress.org/support/topic/hack-to-fix-current_user_can_publish_posts-plugin-conflict-on-reorder-screen) back a bit, FYI.
