### ISSUE TITLE
Issue using ReOrder Post within Categories

### ISSUE THREAD

**Issue by davidarago** [aurovrata/ReOrder-posts-within-categories#25]
Hi,

We are having an issue with the ReOrder plugin where from time to time the content producer creates a post, assigns the post to a category and the new post does not appears in the page. When we go to the “Plugin Dashboard” and select the category to reorder. We have the Use the manual sorting for this category? Yes and Override ‘orderby’ query attribute. But the new post does not show up, until the content producer clicks on the Reset Order.

We have between 3000 to 10000 posts in each category. It is happening the categories with the upper and lower limit.

We are using V2.12.5

**Comment by aurovrata** [comment]
Did you upgrade from v1.X?  If so did you delete the old custom table used by v1.x?

**Comment by aurovrata** [comment]
I just tested this on my server, and new posts show up as expected.  So something in your setup is causing the `save_post` filter to fail to trigger the new post addition to the manual rank.

If you need me to debug your setup, I can do so for a fee.  If I find the bug is **not** related to your setup but due to the plugin, I will not charge you.  You can reach me on "vrata at syllogic dot in"

**Comment by davidarago** [comment]
Hi.  What is the name of the old table.  I think that we purchase your plugin when it was version 2, but I am not sure.

Also, I notice that you have some debug code on your plugin, is there a way that I can set the debug flag from within your plugin configuration?  I would like to do some more debugging myself before we consider your suggestion to help us debug.  Thanks.

**Comment by aurovrata** [comment]
since this is just a discussion about an issue and there isn't a bug/feature request, I would kindly request you to use the support forum so other may find your post.

I am closing this and will respond on the WP forum instead.
